export const GLOSSARY = Object.freeze({
  Agent: "智能体",
  Model: "模型",
  Tool: "工具",
  Skill: "技能",
  Prompt: "提示词",
  Workflow: "工作流",
  Heartbeat: "心跳",
});

const common = [
  // Navigation and shared controls
  ["Dashboard", "仪表盘"],
  ["DASHBOARD", "仪表盘"],
  ["INBOX", "收件箱"],
  ["TASKS", "任务"],
  ["PROJECTS", "项目"],
  ["ROUTINES", "例行任务"],
  ["ARTIFACTS", "产出物"],
  ["AGENTS", "智能体"],
  ["SKILLS", "技能"],
  ["CONNECTORS", "连接器"],
  ["AUDIT", "审计"],
  ["Work", "工作"],
  ["Org", "组织"],
  ["Recent Tasks", "最近任务"],
  ["SEARCH", "搜索"],
  ["Relevance", "相关性"],
  ["Recently updated", "最近更新"],
  ["Newest created", "最新创建"],
  ["Sort by", "排序依据"],
  ["Sort results", "排序搜索结果"],
  ["Open account menu", "打开账户菜单"],
  ["View profile", "查看个人资料"],
  ["Edit profile", "编辑个人资料"],
  ["Documentation", "文档"],
  ["Switch to light mode", "切换到浅色模式"],
  ["Switch to dark mode", "切换到深色模式"],
  ["New agent progress", "新建智能体进度"],
  ["1. Name", "1. 名称"],
  ["2. Adapter", "2. 适配器"],
  ["Meet your next agent", "认识你的新智能体"],
  ["Start with a name. Make them your own.", "先给它起个名字，让它成为你的专属智能体。"],
  ["e.g. Darnold", "例如：Darnold"],
  ["Invite an external agent", "邀请外部智能体"],
  ["Choose adapter", "选择适配器"],
  ["Choose an adapter", "选择适配器"],
  ["Loading adapters…", "正在加载适配器…"],
  ["Configure agent", "配置智能体"],
  ["Generate a one-time onboarding prompt for an external agent. An organization admin must approve its join request before it can claim an API key.", "为外部智能体生成一次性接入提示词。该智能体必须先由组织管理员批准加入申请，才能获取 API Key。"],
  ["Optional message for the agent", "给智能体的可选消息"],
  ["Generate onboarding prompt", "生成接入提示词"],
  ["Generating…", "正在生成…"],
  ["Agent onboarding prompt", "智能体接入提示词"],
  ["Send this one-time prompt to the agent that should join your organization.", "将这段一次性提示词发送给需要加入你组织的智能体。"],
  ["Clipboard unavailable. Copy the prompt manually from the field above.", "无法使用剪贴板。请从上方字段手动复制提示词。"],
  ["Copied prompt", "已复制提示词"],
  ["Copy prompt", "复制提示词"],
  ["New agent", "新建智能体"],
  ["Configure your agent", "配置你的智能体"],
  ["Confirmation", "确认"],
  ["Use a Gemini API key, or an existing supported Gemini CLI login on the selected environment's host.", "使用 Gemini API Key，或使用所选环境主机上已有且受支持的 Gemini CLI 登录。"],
  ["Optional if already configured", "如已配置则可留空"],
  ["Or use an organization secret", "或使用组织密钥"],
  ["Select secret…", "选择密钥…"],
  ["New keys are saved as organization secrets when you finish setup.", "完成设置后，新密钥将保存为组织密钥。"],
  ["Environment", "环境"],
  ["Default: Local", "默认：本机"],
  ["Finish setup", "完成设置"],
  ["Search tasks...", "搜索任务…"],
  ["Recovery needed", "需要恢复"],
  ["Recovery needed — open the source task to act.", "需要恢复 — 打开源任务以处理。"],
  ["Recovery needed — retries used up", "需要恢复 — 重试次数已用尽"],
  ["Recovery needed — retries used up. Open the source task to act.", "需要恢复 — 重试次数已用尽。打开源任务以处理。"],
  ["Desktop task rows", "桌面端任务行"],
  ["Choose which task columns stay visible", "选择要显示的任务列"],
  ["Columns", "列"],
  ["Responsible", "负责人"],
  ["Kicked off by", "发起者"],
  ["Workspace", "工作区"],
  ["Parent task", "父任务"],
  ["Parent Task", "父任务"],
  ["Tags", "标签"],
  ["Last updated", "最近更新"],
  ["Task state chip on the left edge.", "左侧的任务状态标记。"],
  ["Task state icon on the leading edge.", "左侧的任务状态图标。"],
  ["Ticket identifier like PAP-1009.", "任务编号，例如 PAP-1009。"],
  ["Task identifier like PAP-1009 on the trailing edge.", "右侧的任务编号，例如 PAP-1009。"],
  ["Responsible agent or board user.", "负责此任务的智能体或管理者。"],
  ["Board user or agent who created the task.", "创建此任务的管理者或智能体。"],
  ["Linked project pill with its color.", "关联项目及其标识颜色。"],
  ["Execution or project workspace used for the task.", "此任务使用的执行或项目工作区。"],
  ["Parent task identifier and title.", "父任务编号和标题。"],
  ["Task labels and tags.", "任务标签。"],
  ["Latest visible activity time.", "最近可见的活动时间。"],
  ["Date group separators", "日期分组线"],
  ["Show Today, Yesterday, and Earlier rules on newest-first task lists.", "在按最新时间排序的任务列表中显示“今天”“昨天”和“更早”的分组线。"],
  ["Reset defaults", "恢复默认设置"],
  ["status, id, updated", "状态、编号、更新时间"],
  ["Filters", "筛选"],
  ["Filter", "筛选"],
  ["Quick filters", "快捷筛选"],
  ["Visibility", "可见范围"],
  ["No responsible", "无负责人"],
  ["Creator", "创建者"],
  ["Search creators...", "搜索创建者…"],
  ["No creators match.", "没有匹配的创建者。"],
  ["Live runs only", "仅显示正在运行的任务"],
  ["Hide routine runs", "隐藏例行任务的运行"],
  ["List view", "列表视图"],
  ["Board view", "看板视图"],
  ["Enable parent-child nesting", "启用父子任务嵌套"],
  ["Disable parent-child nesting", "关闭父子任务嵌套"],
  ["Cancelled", "已取消"],
  ["Label", "标签"],
  ["Comment", "评论"],
  ["Doc", "文档"],
  ["Artifact", "产出物"],
  ["No options", "没有可选项"],
  ["Open items", "未关闭的任务"],
  ["Clear all filters", "清除所有筛选条件"],
  ["Search assignees…", "搜索负责人…"],
  ["Search assignees...", "搜索负责人…"],
  ["Search projects…", "搜索项目…"],
  ["Search projects...", "搜索项目…"],
  ["Search labels…", "搜索标签…"],
  ["No assignees", "没有负责人"],
  ["No assignee", "未指定负责人"],
  ["No projects", "没有项目"],
  ["No project", "无项目"],
  ["No labels", "没有标签"],
  ["Add reviewer, approver, or watchdog", "添加审阅者、审批者或监督者"],
  ["editable markdown", "可编辑的 Markdown 内容"],
  ["Recent Activity", "最近活动"],
  ["Routines", "例行任务"],
  ["Artifacts", "产出物"],
  ["Search artifacts...", "搜索产出物…"],
  ["Installed", "已安装"],
  ["Discover", "发现"],
  ["AUTHOR", "创作"],
  ["Author", "创作"],
  ["Skills you create, edit, and test.", "创建、编辑和测试你自己的技能。"],
  ["My Skills", "我的技能"],
  ["Search installed skills", "搜索已安装的技能"],
  ["Search installed skills…", "搜索已安装的技能…"],
  ["Search discoverable skills", "搜索可发现的技能"],
  ["Search discoverable skills…", "搜索可发现的技能…"],
  ["Discover skills", "发现技能"],
  ["Browse skills from every available source.", "浏览所有可用来源的技能。"],
  ["Most agents", "智能体最多"],
  ["Most stars", "星标最多"],
  ["Most forks", "复刻最多"],
  ["Alphabetical", "按字母顺序"],
  ["Create new skill", "新建技能"],
  ["Import from path or URL", "从路径或网址导入"],
  ["Import skills from project", "从项目导入技能"],
  ["Scan project workspaces for skills", "扫描项目工作区中的技能"],
  ["All sources", "所有来源"],
  ["Source", "来源"],
  ["Select skill", "选择技能"],
  ["Loading skills...", "正在加载技能…"],
  ["Create a new skill", "新建技能"],
  ["No installed skills yet. Discover a skill or create one.", "尚未安装技能。可以发现或创建技能。"],
  ["No skills are available to discover yet.", "目前没有可发现的技能。"],
  ["No skills match your filters.", "没有符合筛选条件的技能。"],
  ["No skills in this view yet.", "此视图中暂无技能。"],
  ["Audit", "审计"],
  ["New", "新建"],
  ["Loading task…", "正在加载任务…"],
  ["Blocked by", "被以下任务阻塞"],
  ["Still blocked by", "仍被以下任务阻塞"],
  ["Stopped", "已停止"],
  ["Worked", "已执行"],
  ["Run failed", "运行失败"],
  ["Trace incomplete", "跟踪信息不完整"],
  ["Inspect run", "检查运行"],
  ["Re-run with provider trace", "重新运行并记录提供方跟踪信息"],
  ["On behalf of", "代表"],
  ["GitHub identity history", "GitHub 身份历史"],
  ["No persisted transcript for this run.", "此次运行没有保存对话记录。"],
  ["Waiting for transcript...", "正在等待对话记录…"],
  ["Failure details", "失败详情"],
  ["Error:", "错误："],
  ["adapter result JSON", "适配器结果 JSON"],
  ["stderr excerpt", "标准错误输出摘录"],
  ["stdout excerpt", "标准输出摘录"],
  ["Nice", "易读"],
  ["Raw", "原始"],
  ["On-demand", "按需触发"],
  ["Automation", "自动触发"],
  ["Assignment", "任务分配"],
  ["RUNTIME", "运行环境"],
  ["Runtime", "运行环境"],
  ["GOVERNANCE", "治理"],
  ["Governance", "治理"],
  ["Secrets & variables", "密钥与变量"],
  ["Permissions / Trust", "权限与信任"],
  ["API Keys", "API 密钥"],
  ["Revisions", "修订记录"],
  ["ENTRY", "入口"],
  ["markdown file", "Markdown 文件"],
  ["Saved", "已保存"],
  ["Browse skills store", "浏览技能库"],
  ["Agent identity", "智能体身份"],
  ["AI connection", "AI 连接"],
  ["Responsible user’s connection", "负责人的连接"],
  ["Other users’ tasks use their own OpenAI connection.", "其他用户的任务使用其各自的 OpenAI 连接。"],
  ["For you:", "对你而言："],
  ["Other users’ tasks use their own", "其他用户的任务使用各自的"],
  ["connection.", "连接。"],
  ["Connect another account", "连接其他账户"],
  ["Default", "默认"],
  ["Thinking effort", "思考强度"],
  ["Auto", "自动"],
  ["Execution engine", "执行引擎"],
  ["Default (ACP)", "默认（ACP）"],
  ["Bypass sandbox", "绕过沙盒"],
  ["Enable search", "启用搜索"],
  ["Fast mode", "快速模式"],
  ["Environment variables", "环境变量"],
  ["No environment variables", "没有环境变量"],
  ["Add variable", "添加变量"],
  ["Set the KEY to the env var name the process expects, for example GH_TOKEN. Choose a secret to resolve a stored value at run start. PAPERCLIP_* variables are injected automatically.", "将 KEY 设为进程需要的环境变量名，例如 GH_TOKEN。可选择一个密钥，以便在运行开始时解析存储值。PAPERCLIP_* 变量会自动注入。"],
  ["Run Policy", "运行策略"],
  ["Heartbeat on interval", "按间隔执行心跳"],
  ["Advanced Run Policy", "高级运行策略"],
  ["Secret access", "密钥访问"],
  ["Secrets this agent can reach. Env-var bindings are injected at run start; API-access bindings are fetched on demand via the run-bound agent API and never written to the environment.", "此智能体可访问的密钥。环境变量绑定会在运行开始时注入；API 访问绑定仅在需要时通过当前运行的智能体 API 获取，不写入环境变量。"],
  ["No secrets are bound to this agent yet.", "此智能体尚未绑定密钥。"],
  ["API ACCESS (NO ENV VAR)", "API 访问（不使用环境变量）"],
  ["API access (no env var)", "API 访问（不使用环境变量）"],
  ["Add API access", "添加 API 访问权限"],
  ["Fetched on demand via the run-bound agent API. Never written to the environment. The agent reads them by alias through GET /agents/me/secrets.", "按需通过当前运行的智能体 API 获取，不写入环境变量。智能体通过 GET /agents/me/secrets 按别名读取。"],
  ["Fetched on demand via the run-bound agent API. Never written to the environment. The agent reads them by alias through", "按需通过当前运行的智能体 API 获取，不写入环境变量。智能体通过以下接口按别名读取："],
  ["Discard", "放弃更改"],
  ["Save changes", "保存更改"],
  ["Effective access", "当前有效权限"],
  ["This is exactly the tool set Paperclip will accept for", "这正是 Paperclip 允许该智能体使用的工具集："],
  [". Profile and policy edits are reflected within ~5 seconds. The agent's prompt can narrow this list but", "。配置和策略的修改约在 5 秒内生效。智能体的提示词可以缩小此列表，但"],
  ["cannot expand it", "不能扩大权限"],
  ["— everything else is blocked by default.", "——其他工具默认全部阻止。"],
  ["GitHub identity", "GitHub 身份"],
  ["Use responsible person's GitHub", "使用负责人的 GitHub 账户"],
  ["At run start, Paperclip uses the personal GitHub connection of the person responsible for the task.", "运行开始时，Paperclip 使用任务负责人的个人 GitHub 连接。"],
  ["Connect my GitHub", "连接我的 GitHub"],
  ["Use a dedicated account", "使用专用账户"],
  ["Installed apps", "已安装的应用"],
  ["Has access means the app is permitted. Installed means its tools are added to this agent's runtime context.", "“有访问权限”表示允许使用该应用；“已安装”表示其工具会加入此智能体的运行上下文。"],
  ["Installed for all", "已为所有智能体安装"],
  ["Installed from the app page for every agent. Remove the all-agents install there.", "已在应用页面为所有智能体安装。请在该页面移除全体安装。"],
  ["Allowed tools", "允许使用的工具"],
  ["No tools are allowed for this agent. Bind a tool profile to grant access.", "此智能体目前不能使用任何工具。绑定工具配置以授予权限。"],
  ["Why these tools?", "为什么是这些工具？"],
  ["Access profiles", "访问配置"],
  ["Check access", "检查权限"],
  ["No active profile applies to this agent, so it has no allowed tools.", "没有适用于此智能体的有效配置，因此没有获准使用的工具。"],
  ["Active policies", "生效中的策略"],
  ["No enabled policy currently mutates this agent's allow list.", "目前没有已启用的策略更改此智能体的允许列表。"],
  ["Unavailable tools", "不可用的工具"],
  ["Every known tool this agent could name is allowed.", "此智能体可调用的所有已知工具均获准使用。"],
  ["Tools the agent could name but Paperclip would block:", "智能体可能调用、但会被 Paperclip 阻止的工具："],
  ["Debugging", "调试"],
  ["Capture raw provider traces", "记录提供方原始跟踪信息"],
  ["Test your agent", "测试智能体"],
  ["Check that your runtime and model can respond.", "检查运行环境和模型是否能够响应。"],
  ["Run test", "运行测试"],
  ["Permitted-only apps do not add context cost.", "仅获准使用、未安装的应用不会增加上下文开销。"],
  ["Trust", "信任"],
  ["Trust preset", "信任预设"],
  ["Standard", "标准"],
  ["Low-trust review", "低信任度审核"],
  ["Organization-visible collaboration. This is the default for normal work.", "在组织内可见的协作。这是普通工作的默认设置。"],
  ["Advanced permissions remain editable through the EE permissions extension when installed.", "安装 EE 权限扩展后，仍可编辑高级权限。"],
  ["Can create new agents", "可创建新智能体"],
  ["Lets this agent create or hire agents. This also grants task assignment authority.", "允许此智能体创建或招聘智能体，并授予任务分配权限。"],
  ["Can create/import skills", "可创建或导入技能"],
  ["Lets this agent install, import, create, and scan organization skills without creating agents.", "允许此智能体安装、导入、创建和扫描组织技能，无需创建智能体。"],
  ["Can assign tasks", "可分配任务"],
  ["Enabled automatically while this agent can create new agents.", "当此智能体获准创建新智能体时自动启用。"],
  ["Create API Key", "创建 API 密钥"],
  ["API keys allow this agent to authenticate calls to the Paperclip server.", "API 密钥可用于此智能体向 Paperclip 服务器发起身份验证调用。"],
  ["No active API keys.", "没有有效的 API 密钥。"],
  ["Configuration Revisions", "配置修订记录"],
  ["No configuration revisions yet.", "暂无配置修订记录。"],
  ["Search inbox…", "搜索收件箱…"],
  ["Archive", "归档"],
  ["Backlog", "待规划"],
  ["In Progress", "进行中"],
  ["Mine", "我的"],
  ["Unread", "未读"],
  ["Recent", "最近"],
  ["Retrying…", "正在重试…"],
  ["Plan mode", "规划模式"],
  ["Ask mode", "提问模式"],
  ["Reviewer", "审阅者"],
  ["Approver", "审批者"],
  ["Watchdog", "监督者"],
  ["Start date", "开始日期"],
  ["Parked - assignee will not be woken", "暂存任务，不会唤醒负责人"],
  ["Executable - assignee will be woken", "可执行任务，会唤醒负责人"],
  ["Try again", "重试"],
  ["Configuration", "配置"],
  ["Assign Task", "分配任务"],
  ["Run now", "立即运行"],
  ["Run with provider trace", "运行并记录提供方跟踪信息"],
  ["Clear error", "清除错误"],
  ["Latest Run", "最近一次运行"],
  ["Identity", "身份"],
  ["Role", "角色"],
  ["Title", "头衔"],
  ["Not set", "未设置"],
  ["Direct reports", "直接下属"],
  ["Harness / Runtime", "执行器 / 运行环境"],
  ["Configure", "配置"],
  ["Adapter", "适配器"],
  ["Adapter default", "适配器默认值"],
  ["Session", "会话"],
  ["Last run", "上次运行"],
  ["Capabilities", "能力"],
  ["No capability summary has been added.", "尚未添加能力摘要。"],
  ["Manage", "管理"],
  ["No skills enabled.", "未启用技能。"],
  ["See All →", "查看全部 →"],
  ["Logo", "标志"],
  ["Hiring", "招聘"],
  ["Require board approval for new hires", "新聘智能体须经管理者审批"],
  ["Interaction governance", "交互治理"],
  ["Thread interactions are open by default:", "任务对话交互默认开放："],
  ["Anyone", "任何人"],
  ["Default policy", "默认策略"],
  ["Human only", "仅限人工"],
  ["Suggested tasks", "建议的任务"],
  ["Anyone (default)", "任何人（默认）"],
  ["No cap", "无上限"],
  ["Ask user questions", "向用户提问"],
  ["Checkbox confirmations", "勾选确认"],
  ["Item verdicts", "逐项裁决"],
  ["Connection requests", "连接请求"],
  ["Deployment and auth", "部署与身份验证"],
  ["Local trusted", "本地可信"],
  ["Auth readiness", "认证就绪状态"],
  ["Bootstrap invite", "初始化邀请"],
  ["Censor username in logs", "在日志中隐藏用户名"],
  ["Backup retention", "备份保留期"],
  ["AI feedback sharing", "AI 反馈共享"],
  ["Danger Zone", "危险操作"],
  ["Archive organization", "归档组织"],
  ["Inference spend, platform fees, credits, and live quota windows.", "推理费用、平台收费、抵扣额和实时配额窗口。"],
  ["Month to Date", "本月至今"],
  ["Last 7 Days", "最近 7 天"],
  ["Last 30 Days", "最近 30 天"],
  ["Year to Date", "今年至今"],
  ["All Time", "全部时间"],
  ["No monthly cap configured", "未设置每月上限"],
  ["Finance net", "财务净额"],
  ["Finance events", "财务事件"],
  ["Providers", "提供商"],
  ["Billers", "账单方"],
  ["Finance", "财务"],
  ["Inference ledger", "推理流水"],
  ["Finance ledger", "财务流水"],
  ["Debits", "支出"],
  ["Credits", "抵扣"],
  ["Net", "净额"],
  ["Estimated", "估算"],
  ["By agent", "按智能体"],
  ["By project", "按项目"],
  ["Recent financial events", "最近财务事件"],
  ["Budget control plane", "预算控制面板"],
  ["Active incidents", "当前超额事件"],
  ["Pending approvals", "待审批"],
  ["Paused agents", "已暂停的智能体"],
  ["Paused projects", "已暂停的项目"],
  ["in the organization — the board or any agent, including the one that asked — can respond. Narrow a kind only when you need to.", "组织中的管理者或任何智能体（包括发起请求的智能体）都可以响应。仅在必要时限制某类交互。"],
  ["is the audience new cards get when the requester does not ask for one;", "是请求者未指定时，新卡片默认采用的响应对象；"],
  ["Cap", "上限"],
  ["Kind", "类型"],
  ["Confirmations", "确认"],
  ["Local trusted mode is optimized for a local operator. Browser requests run as local board context and no sign-in is required.", "本地可信模式面向本机操作者。浏览器请求以本地管理者身份运行，无需登录。"],
  ["Ready", "已就绪"],
  ["Bootstrap status", "初始化状态"],
  ["None", "无"],
  ["Daily", "每天"],
  ["Weekly", "每周"],
  ["Monthly", "每月"],
  ["days", "天"],
  ["1 week", "1 周"],
  ["2 weeks", "2 周"],
  ["4 weeks", "4 周"],
  ["1 month", "1 个月"],
  ["3 months", "3 个月"],
  ["6 months", "6 个月"],
  ["Always allow", "始终允许"],
  ["Don't allow", "不允许"],
  ["Read our terms of service", "阅读服务条款"],
  ["Share voted AI outputs automatically.", "自动共享已评价的 AI 输出。"],
  ["Keep voted AI outputs local only.", "已评价的 AI 输出仅保存在本地。"],
  ["Archive this organization to hide it from the sidebar. This persists in the database.", "归档此组织并在侧栏中隐藏；归档状态会保存在数据库中。"],
  ["Recent agent executions across the organization. Open a run to inspect its transcript, output, and task context.", "组织内最近的智能体运行记录。打开一条记录可查看转录、输出和任务上下文。"],
  ["All statuses", "所有状态"],
  ["automation run", "自动运行"],
  ["assignment run", "任务分配运行"],
  ["on demand run", "按需运行"],
  ["Showing the", "显示"],
  ["most recent runs.", "条最近的运行记录。"],
  ["Request-scoped inference spend for the selected period.", "所选时段内按请求统计的推理费用。"],
  ["Account-level charges that do not map to a single inference request.", "无法归入单次推理请求的账户级费用。"],
  ["Refunds, offsets, and credit returns", "退款、抵扣和额度返还"],
  ["Debit minus credit for the selected period", "所选时段的支出减去抵扣"],
  ["Estimated debits that are not yet invoice-authoritative", "尚未经正式账单确认的估算支出"],
  ["What each agent consumed in the selected period.", "各智能体在所选时段的消耗。"],
  ["Run costs attributed through project-linked tasks.", "通过关联项目的任务归集的运行费用。"],
  ["Top-ups, fees, credits, commitments, and other non-request charges.", "充值、收费、抵扣、承诺支出及其他非请求级费用。"],
  ["Hard-stop spend limits for agents and projects. Provider subscription quota stays separate and appears under Providers.", "智能体和项目的硬性费用上限。提供商订阅配额单独计算，显示在“提供商”下。"],
  ["Open soft or hard threshold crossings", "尚未处理的软性或硬性阈值超限"],
  ["Budget override approvals awaiting board action", "等待管理者处理的预算超额审批"],
  ["Agent heartbeats blocked by budget", "因预算限制而阻止的智能体心跳"],
  ["Project execution blocked by budget", "因预算限制而阻止的项目执行"],
  ["Add account", "添加账户"],
  ["Connect", "连接"],
  ["narrows every request of that kind and can never widen one. Tool-approval confirmations always stay", "会限制该类型的所有请求，且不能放宽范围。工具审批确认始终为"],
  ["Hide the username segment in home-directory paths and similar operator-visible log output. Standalone username mentions outside of paths are not yet masked in the live transcript view. This is off by default.", "在主目录路径及类似的操作者可见日志中隐藏用户名。实时转录中路径之外单独出现的用户名尚不会被遮蔽。此功能默认关闭。"],
  ["Configure how long automatic database backups are retained. Backups run roughly every hour and are compressed with gzip. Within the daily window all backups are kept; beyond that, one backup per week and one per month are preserved.", "设置自动数据库备份的保留时长。备份约每小时运行一次，并使用 gzip 压缩。每日保留窗口内保存全部备份；超过该窗口后，每周和每月各保留一份。"],
  ["Control whether thumbs up and thumbs down votes can send the voted AI output to Paperclip Labs. Votes are always saved locally.", "控制点赞或点踩时是否可将被评价的 AI 输出发送给 Paperclip Labs。评价始终会保存在本地。"],
  ["No default is saved yet. The next thumbs up or thumbs down choice will ask once and then save the answer here.", "尚未保存默认选项。下次点赞或点踩时会询问一次，并在此保存你的选择。"],
  ["Sign out of this Paperclip instance. You will be redirected to the login page.", "退出此 Paperclip 实例，并跳转到登录页面。"],
  ["Custom", "自定义"],
  ["Inference spend", "推理费用"],
  ["usage", "用量"],
  ["No finance events yet. Add account-level charges once biller invoices or credits land.", "还没有财务事件。收到账单方发票或抵扣额度后，可添加账户级费用。"],
  ["No budget policies yet. Set agent and project budgets from their detail pages, or use the existing organization monthly budget control.", "还没有预算策略。可在智能体和项目详情页设置预算，或使用现有的组织每月预算控制。"],
  ["To retest the first-use prompt in local dev, remove the", "要在本地开发环境重新测试首次使用提示，请移除"],
  ["key from the", "键，位置在"],
  ["JSON row for this instance, or set it back to", "此实例的 JSON 记录中；也可将其设回"],
  [". Unset and", "。未设置以及"],
  ["both mean no default has been chosen yet.", "都表示尚未选择默认选项。"],
  ["· out", "· 输出"],
  ["Connected", "已连接"],
  ["Connected by", "连接者"],
  ["My OpenAI subscription", "我的 OpenAI 订阅"],
  ["ChatGPT subscription", "ChatGPT 订阅"],
  ["Personal", "个人"],
  ["Today", "今天"],
  ["just now", "刚刚"],
  ["Sort:", "排序："],
  ["Sort", "排序"],
  ["Group", "分组"],
  ["New folder", "新建文件夹"],
  ["Leave", "退出"],
  ["Images", "图片"],
  ["Videos", "视频"],
  ["Documents", "文档"],
  ["Text", "文本"],
  ["Files", "文件"],
  ["Overview", "概览"],
  ["Inbox", "收件箱"],
  ["Tasks", "任务"],
  ["Task", "任务"],
  ["Projects", "项目"],
  ["Project", "项目"],
  ["Goals", "目标"],
  ["Goal", "目标"],
  ["Agents", "智能体"],
  ["Agent", "智能体"],
  ["Models", "模型"],
  ["Model", "模型"],
  ["Tools", "工具"],
  ["Tool", "工具"],
  ["Skills", "技能"],
  ["Skill", "技能"],
  ["Prompts", "提示词"],
  ["Prompt", "提示词"],
  ["Workflows", "工作流"],
  ["Workflow", "工作流"],
  ["Heartbeat", "心跳"],
  ["Heartbeats", "心跳"],
  ["Activity", "活动"],
  ["Timeline", "时间线"],
  ["Approvals", "审批"],
  ["Approval", "审批"],
  ["Costs", "费用"],
  ["Budget", "预算"],
  ["Settings", "设置"],
  ["Company", "公司"],
  ["Companies", "公司"],
  ["Organization", "组织"],
  ["Organizations", "组织"],
  ["Search", "搜索"],
  ["Notifications", "通知"],
  ["Plugins", "插件"],
  ["Adapters", "适配器"],
  ["Connectors", "连接器"],
  ["Secrets", "密钥"],
  ["Usage", "用量"],
  ["Help", "帮助"],
  ["Profile", "个人资料"],
  ["Users", "用户"],
  ["Back to app", "返回应用"],
  ["Environments", "环境"],
  ["Access", "访问控制"],
  ["Export", "导出"],
  ["Import", "导入"],
  ["Experimental features", "实验性功能"],
  ["Experimental Features", "实验性功能"],
  ["ALL-TIME TOKENS", "累计 Token 用量"],
  ["OPEN ASSIGNED", "已分配的未完成任务"],
  ["7-DAY ACTIONS", "近 7 天操作"],
  ["LAST 7 DAYS", "过去 7 天"],
  ["LAST 30 DAYS", "过去 30 天"],
  ["ALL TIME", "全部时间"],
  ["Touched", "触及任务"],
  ["Comments", "评论"],
  ["Actions", "操作"],
  ["Tokens", "Token"],
  ["Spend", "支出"],
  ["TOKENS / DAY", "每日 Token 用量"],
  ["COMPLETIONS", "完成任务数"],
  ["Recent tasks", "最近任务"],
  ["Recent activity", "最近活动"],
  ["Control how your account appears in the sidebar and other board surfaces.", "管理你的账户在侧边栏和管理界面中的显示方式。"],
  ["Change photo", "更换头像"],
  ["Display name", "显示名称"],
  ["Email", "电子邮箱"],
  ["Shown in the sidebar account footer and comment author surfaces.", "显示在侧边栏账户区域和评论作者信息中。"],
  ["Email is managed by your auth session and is read-only here.", "电子邮箱由登录会话管理，此处仅可查看。"],
  ["Save profile", "保存个人资料"],
  ["Keyboard shortcuts", "键盘快捷键"],
  ["Enable app keyboard shortcuts, including inbox navigation and global shortcuts like creating tasks or toggling panels. This applies only to your account, across all organizations and devices. Off by default.", "启用应用内键盘快捷键，包括收件箱导航、创建任务及切换面板。此设置仅适用于你的账户，并在所有组织和设备间生效；默认关闭。"],
  ["Let agents tidy my inbox", "让智能体整理我的收件箱"],
  ["Choose whether the agents you manage may archive tasks out of your inbox on your behalf. You can undo any archive, and every agent archive is attributed in the task's properties.", "选择是否允许你管理的智能体代你归档收件箱中的任务。归档可撤销，每次操作都会在任务属性中注明对应智能体。"],
  ["Any of my agents", "我管理的所有智能体"],
  ["Let any agent you manage archive tasks out of your inbox.", "允许你管理的任意智能体归档收件箱中的任务。"],
  ["Only chosen agents", "仅指定智能体"],
  ["Restrict inbox tidying to the agents you pick below.", "仅允许下方选定的智能体整理收件箱。"],
  ["Off", "关闭"],
  ["Agents can never archive tasks from your inbox.", "智能体无法归档收件箱中的任务。"],
  ["Loading inbox agent policy…", "正在加载收件箱智能体策略…"],
  ["Inbox agent archiving policy", "收件箱智能体归档策略"],
  ["Agents allowed to tidy my inbox", "允许整理收件箱的智能体"],
  ["Loading profile...", "正在加载个人资料…"],
  ["Opt into features that are still being evaluated before they become default behavior.", "选择启用尚在评估、未成为默认行为的功能。"],
  ["Experimental features may break at any time.", "这些实验性功能可能随时失效。"],
  ["These features are opt-in and come with no compatibility guarantees. They may change, break, or be removed without notice. Avoid relying on them for critical or production workflows.", "这些功能需主动启用，且不保证兼容性；可能随时更改、失效或移除。请勿在关键或生产工作流中依赖它们。"],
  ["Optional product features that are still being evaluated.", "仍在评估中的可选产品功能。"],
  ["Agent Chat", "智能体聊天"],
  ["Talk to each agent in one ongoing conversation. Clarify goals and create tasks for execution.", "在持续的会话中与智能体沟通，明确目标并创建待执行的任务。"],
  ["Beta skills", "测试版技能"],
  ["Allow agents to pin beta releases of the Paperclip core skill. Disabling this returns every agent to the default live skill without removing saved pins.", "允许智能体固定使用 Paperclip 核心技能的测试版。关闭后，所有智能体恢复使用默认正式版，但不会删除已保存的版本选择。"],
  ["Instance Access", "实例访问控制"],
  ["Search users, manage instance-admin status, and control which organizations they can access.", "搜索用户、管理实例管理员身份，并控制他们可访问的组织。"],
  ["Search by name or email", "按姓名或邮箱搜索"],
  ["Organization access", "组织访问权限"],
  ["Toggle organization membership for this user. New access defaults to an active operator membership.", "设置此用户的组织成员资格。新增访问权限默认采用活跃操作员身份。"],
  ["Current memberships", "当前成员关系"],
  ["Select a user to inspect instance access.", "选择用户以查看其实例访问权限。"],

  // Settings: general, membership, secrets, import/export, plugins, adapters
  ["Loading general settings...", "正在加载常规设置…"],
  ["Renaming can change this company's task ID prefix. Existing task IDs are renumbered and old task links stop resolving.", "重命名可能更改该组织的任务编号前缀。现有任务编号将重新编排，旧任务链接将失效。"],
  ["Optional organization description", "可选的组织简介"],
  ["Uploading logo...", "正在上传标志…"],
  ["Organization Members", "组织成员"],
  ["Invites", "邀请"],
  ["Pending human joins", "待审核的成员加入申请"],
  ["Invite a person", "邀请成员"],
  ["Generate a human invite link and choose the default access it should request.", "生成成员邀请链接，并选择其默认申请的访问权限。"],
  ["Choose a role", "选择角色"],
  ["Invite history", "邀请记录"],
  ["Review invite status, audience, inviter, and any linked join request.", "查看邀请状态、受邀对象、邀请人及关联的加入申请。"],
  ["No invites have been created for this organization yet.", "该组织尚未创建邀请。"],
  ["No user memberships found for this organization yet.", "该组织尚无用户成员。"],
  ["All secrets", "全部密钥"],
  ["My secrets", "我的密钥"],
  ["Provider vaults", "提供商密钥库"],
  ["Search by name, key, ref", "按名称、键名或引用搜索"],
  ["Import from AWS Secrets Manager", "从 AWS Secrets Manager 导入"],
  ["Bring AWS-managed secrets into Paperclip as external references.", "将 AWS 管理的密钥作为外部引用导入 Paperclip。"],
  ["Import source", "导入来源"],
  ["Choose a GitHub repo or upload a local Paperclip zip package.", "选择 GitHub 仓库或上传本地 Paperclip ZIP 包。"],
  ["GitHub repo", "GitHub 仓库"],
  ["Local zip", "本地 ZIP 文件"],
  ["Choose zip", "选择 ZIP 文件"],
  ["GitHub URL", "GitHub 地址"],
  ["Target", "目标位置"],
  ["Create new organization", "新建组织"],
  ["New organization name", "新组织名称"],
  ["Collision strategy", "冲突处理方式"],
  ["Rename on conflict", "冲突时重命名"],
  ["Skip on conflict", "冲突时跳过"],
  ["Replace existing", "替换现有内容"],
  ["Import preview", "导入预览"],
  ["Package files", "包内文件"],
  ["External Adapters", "外部适配器"],
  ["No external adapters installed", "尚未安装外部适配器"],
  ["Install External Adapter", "安装外部适配器"],
  ["Built-in Adapters", "内置适配器"],
  ["External adapters are alpha.", "外部适配器仍处于早期测试阶段。"],
  ["Package Name", "包名称"],
  ["Version (optional)", "版本（可选）"],
  ["Plugin ID", "插件 ID"],
  ["Plugin Key", "插件键名"],
  ["NPM Package", "NPM 包"],
  ["Local folders", "本地文件夹"],
  ["This plugin does not require any settings.", "此插件无需额外设置。"],
  ["Open Environments", "打开环境设置"],
  ["Account", "账户"],
  ["Log out", "退出登录"],
  ["Sign out", "退出登录"],
  ["Sign in", "登录"],
  ["Refresh", "刷新"],
  ["Loading…", "加载中…"],
  ["Loading...", "加载中..."],
  ["Load more", "加载更多"],
  ["View more", "查看更多"],
  ["Show more", "显示更多"],
  ["Show less", "收起"],
  ["Back", "上一步"],
  ["Next", "下一步"],
  ["Continue", "继续"],
  ["Done", "完成"],
  ["Finish", "完成"],
  ["Close", "关闭"],
  ["Open", "打开"],
  ["Cancel", "取消"],
  ["Save", "保存"],
  ["Saving…", "正在保存…"],
  ["Edit", "编辑"],
  ["Delete", "删除"],
  ["Remove", "移除"],
  ["Create", "创建"],
  ["Add", "添加"],
  ["Update", "更新"],
  ["Confirm", "确认"],
  ["Apply", "应用"],
  ["Retry", "重试"],
  ["Copy", "复制"],
  ["Copied", "已复制"],
  ["View all", "查看全部"],
  ["All", "全部"],
  ["Active", "活跃"],
  ["Paused", "已暂停"],
  ["Running", "运行中"],
  ["Pending", "待处理"],
  ["Completed", "已完成"],
  ["Failed", "失败"],
  ["Enabled", "已启用"],
  ["Disabled", "已停用"],
  ["Status", "状态"],
  ["Name", "名称"],
  ["Description", "描述"],
  ["Type", "类型"],
  ["Created", "创建时间"],
  ["Updated", "更新时间"],

  // Onboarding
  ["Create your first company", "创建你的第一家公司"],
  ["Start by creating a company.", "先创建一家公司。"],
  ["New company", "新建公司"],
  ["Create your first agent", "创建你的第一个智能体"],
  ["Select how this agent will run tasks.", "选择这个智能体执行任务的方式。"],
  ["Company name", "公司名称"],
  ["Organization name", "组织名称"],
  ["Agent name", "智能体名称"],
  ["Adapter type", "适配器类型"],
  ["Connect a model", "连接模型"],
  ["Review", "检查"],
  ["Create company", "创建公司"],
  ["Create organization", "创建组织"],
  ["Create agent", "创建智能体"],
  ["Choose manager…", "选择管理者…"],
  ["Choose", "选择"],
  ["Local Codex agent", "本地 Codex 智能体"],
  ["Local Claude agent", "本地 Claude 智能体"],
  ["More adapter types", "更多适配器类型"],

  // Dashboard
  ["Agents Enabled", "已启用的智能体"],
  ["Error", "错误"],
  ["idle", "空闲"],
  ["Tasks In Progress", "进行中的任务"],
  ["Month Spend", "本月支出"],
  ["Pending Approvals", "待审批"],
  ["Unlimited budget", "预算不限"],
  ["Awaiting board review", "等待管理员审核"],
  ["Run Activity", "运行活动"],
  ["Tasks by Status", "按状态统计任务"],
  ["Success Rate", "成功率"],
  ["Last 14 days", "最近 14 天"],
  ["Succeeded", "成功"],
  ["Recovered", "已恢复"],
  ["Other", "其他"],
  ["In Review", "审核中"],
  ["View all runs", "查看全部运行记录"],
  ["No tasks yet.", "还没有任务。"],
  ["You have no agents.", "你还没有智能体。"],
  ["Review agents", "查看智能体"],
  ["Resume all", "全部恢复"],
  ["Resuming…", "正在恢复…"],
  ["All agents in this organization are paused — nothing will run.", "此组织的所有智能体都已暂停，因此不会执行任何任务。"],

  // Agents
  ["New Agent", "新建智能体"],
  ["Create your first agent to get started.", "创建你的第一个智能体以开始使用。"],
  ["Select an organization to view agents.", "选择一个组织以查看智能体。"],
  ["No agents match the selected status.", "没有符合所选状态的智能体。"],
  ["All agents", "全部智能体"],
  ["Built-in agents", "内置智能体"],
  ["Agent configuration", "智能体配置"],
  ["Agent instructions", "智能体指令"],
  ["Instructions", "指令"],
  ["Manager", "管理者"],
  ["Reports to", "汇报对象"],
  ["Run history", "运行记录"],
  ["Back to runs", "返回运行记录"],
  ["Last heartbeat", "上次心跳"],
  ["Heartbeat interval", "心跳间隔"],
  ["Pause agent", "暂停智能体"],
  ["Resume agent", "恢复智能体"],

  // Tasks and projects
  ["New Task", "新建任务"],
  ["New task", "新建任务"],
  ["Task title", "任务标题"],
  ["Add description...", "添加描述…"],
  ["For", "分配给"],
  ["in", "所属"],
  ["Todo", "待办"],
  ["Upload", "上传"],
  ["Auto mode", "自动模式"],
  ["Discard Draft", "丢弃草稿"],
  ["Create Task", "创建任务"],
  ["Creating...", "正在创建…"],
  ["Create task", "创建任务"],
  ["Task details", "任务详情"],
  ["Assignee", "负责人"],
  ["Assign to", "分配给"],
  ["Priority", "优先级"],
  ["Due date", "截止日期"],
  ["In progress", "进行中"],
  ["To do", "待办"],
  ["Blocked", "已阻塞"],
  ["No tasks found", "未找到任务"],
  ["New Project", "新建项目"],
  ["Add Project", "添加项目"],
  ["My Projects", "我的项目"],
  ["Create project", "创建项目"],
  ["Project details", "项目详情"],
  ["No projects yet", "还没有项目"],
  ["Recurring work definitions that materialize into auditable execution tasks.", "将定期工作定义为可审计的执行任务。"],
  ["Create routine", "创建例行任务"],
  ["All routines", "全部例行任务"],
  ["No active routines. Use Create routine to define the first recurring workflow.", "还没有启用的例行任务。点击“创建例行任务”来定义第一个定期工作流。"],
  ["No artifact stacks yet.", "还没有产出物集合。"],
  ["Installed skills", "已安装的技能"],
  ["Skills available to this organization.", "此组织可用的技能。"],
  ["Review what happened, inspect agent runs, and understand the costs and budget controls behind your organization.", "查看发生的事件、检查智能体运行记录，以及了解组织的费用和预算控制。"],
  ["Runs", "运行记录"],
  ["Budgets", "预算"],
  ["Agent Actions", "智能体操作"],
  ["Responsible user", "负责人"],
  ["All responsible users", "所有负责人"],
  ["Action", "操作"],
  ["All actions", "所有操作"],
  ["Entity", "对象"],
  ["All entities", "所有对象"],
  ["From", "起始时间"],
  ["To", "结束时间"],
  ["Export CSV", "导出 CSV"],
  ["on behalf of", "代表"],
  ["View run", "查看运行记录"],
  ["Recorded by Paperclip — entries can't be edited. Sensitive values are never stored.", "由 Paperclip 记录，条目无法编辑；敏感值不会被保存。"],
  ["Read code and pull requests, comment on issues.", "读取代码和拉取请求，并评论 GitHub 议题。"],
  ["Discover and use connected apps through Composio Connect.", "通过 Composio Connect 发现并使用已连接的应用。"],
  ["Search meeting transcripts, read summaries and action items, and connect meeting-ready routines.", "搜索会议转录、阅读摘要和待办事项，并连接会议相关的例行任务。"],
  ["Search and read Gmail messages and create drafts without enabling mail sending.", "搜索和阅读 Gmail 邮件并创建草稿，不启用邮件发送。"],
  ["Read calendars and manage Google Calendar events.", "读取日历并管理 Google Calendar 日程。"],
  ["Search and read Google Chat conversations and send messages.", "搜索和阅读 Google Chat 对话并发送消息。"],
  ["Read and update Google Docs documents.", "读取和更新 Google Docs 文档。"],
  ["Search, read, create, and copy files in Google Drive.", "在 Google Drive 中搜索、读取、创建和复制文件。"],
  ["Search contacts and directory profiles with the Google People API.", "通过 Google People API 搜索联系人和通讯录资料。"],
  ["Read and update Google Sheets spreadsheets.", "读取和更新 Google Sheets 表格。"],
  ["Read and update Google Slides presentations.", "读取和更新 Google Slides 演示文稿。"],
  ["Search Gmail, Drive, Calendar, and Chat through one read-only Google Workspace search tool.", "通过一个只读的 Google Workspace 搜索工具查询 Gmail、Drive、Calendar 和 Chat。"],
  ["Create, update, and read Linear issues.", "创建、更新和读取 Linear 议题。"],
  ["Read and update pages in your Notion workspace.", "读取和更新 Notion 工作区中的页面。"],
  ["Analyze product usage, errors, feature flags, and experiments with PostHog's hosted MCP server.", "通过 PostHog 托管的 MCP 服务器分析产品使用情况、错误、功能开关和实验。"],
  ["Inspect services and logs, deploy applications, and run commands in your Railway containers.", "检查服务和日志、部署应用，并在 Railway 容器中运行命令。"],
  ["Investigate errors, releases, and production issues.", "排查错误、版本发布和生产环境问题。"],
  ["Search a store's products and policies, and manage shopping carts.", "搜索商店商品和政策，并管理购物车。"],
  ["Send and read messages in your team's channels.", "在团队频道中发送和阅读消息。"],
  ["Reach thousands of apps through your Zapier account.", "通过 Zapier 账户连接数千个应用。"],
  ["Connect your own tool", "连接你自己的工具"],
  ["Add a custom MCP server or paste an existing configuration.", "添加自定义 MCP 服务器，或粘贴现有配置。"],

  // Common settings and dialogs
  ["General", "常规"],
  ["Appearance", "外观"],
  ["Language", "语言"],
  ["Theme", "主题"],
  ["Dark", "深色"],
  ["Light", "浅色"],
  ["System", "跟随系统"],
  ["Instance settings", "实例设置"],
  ["Company settings", "公司设置"],
  ["Members", "成员"],
  ["Permissions", "权限"],
  ["Integrations", "集成"],
  ["Advanced", "高级"],
  ["Experimental", "实验性功能"],
  ["Are you sure?", "确定要继续吗？"],
  ["This action cannot be undone.", "此操作无法撤销。"],
  ["commented on", "评论了"],
  ["read", "阅读了"],
  ["environment lease released", "环境租约已释放"],
  ["environment lease acquired", "已获取环境租约"],
  ["cancelled heartbeat for", "取消了心跳："],
  ["created document for", "为其创建了文档："],
];

const search = [
  ["Backlog", "待规划"],
  ["In Progress", "进行中"],
  ["Cancelled", "已取消"],
  ["Me", "我"],
  ["Unassigned", "未分配"],
  ["Last 24 hours", "最近 24 小时"],
  ["Last 7 days", "最近 7 天"],
  ["Last 30 days", "最近 30 天"],
  ["Last 90 days", "最近 90 天"],
  ["Comments", "评论"],
  ["Search query", "搜索关键词"],
  ["Clear search", "清除搜索词"],
  ["Search tasks, comments, documents, artifacts, agents, projects…", "搜索任务、评论、文档、产出物、智能体和项目…"],
  ["Filter by task status", "按任务状态筛选"],
  ["Find blocked work", "查找受阻的工作"],
  ["Use your current board user", "使用当前管理者账户"],
  ["Quote multi-word project names", "含空格的项目名请加引号"],
  ["Filter by issue label", "按任务标签筛选"],
  ["Filter by priority", "按优先级筛选"],
  ["Updated in the last 7 days", "最近 7 天内更新"],
  ["Type to search organization memory.", "输入关键词，搜索组织中的内容。"],
  ["Tasks, comments, plan documents, artifacts, agents, projects — same surface, ranked by relevance.", "任务、评论、计划文档、产出物、智能体和项目统一搜索，并按相关性排序。"],
  ["Recent searches", "最近搜索"],
  ["Identifier lookup:", "按编号查找："],
  ["type", "输入"],
  ["to jump straight to a task.", "可直达任务。"],
  ["Quoted phrases:", "精确短语："],
  ["⌘K:", "⌘K："],
  ["wrap a phrase in quotes to match the exact sequence.", "将短语放入引号中，以匹配完全相同的内容。"],
  ["reopens the command palette pre-seeded with your current query.", "重新打开命令面板，并预填当前搜索词。"],
  ["Try", "试试"],
  ["or", "或"],
  ["Couldn’t run that search", "无法执行搜索"],
  ["The request failed.", "请求失败。"],
  ["Your input and filters are still here, so", "搜索词和筛选条件仍已保留，因此"],
  ["you can retry or fall back to the Tasks filter.", "你可以重试，或改用任务筛选。"],
  ["Open Tasks filter view", "打开任务筛选视图"],
  ["Search all scopes", "搜索所有范围"],
  ["Create task from this query", "按此搜索词创建任务"],
  ["Try fewer tokens or a single distinctive term.", "减少关键词，或只用一个有辨识度的词。"],
  ["Use an identifier shortcut like", "也可直接输入任务编号，例如"],
  ["Wrap multi-word phrases in quotes.", "多词短语请加引号。"],
  ["Updating…", "正在更新…"],
  ["No results with these filters", "当前筛选条件下没有结果"],
  ["Loosen a filter", "放宽筛选条件"],
  ["Remove", "移除"],
];

export const PHRASES = Object.freeze([
  ...common.map(([source, target]) => ({ source, target })),
  ...search.map(([source, target]) => ({ source, target, context: "search" })),
  { source: "Me", target: "我", context: "issue-filter" },
  { source: "Title", target: "标题", context: "task-sort" },
  { source: "Local", target: "本机", context: "environment-choice" },
  { source: "Comment", target: "评论", context: "search-result" },
  { source: "Doc", target: "文档", context: "search-result" },
  { source: "Artifact", target: "产出物", context: "search-result" },
  { source: "Issues", target: "任务", context: "navigation" },
  { source: "Issue", target: "任务", context: "navigation" },
  { source: "Run", target: "运行", context: "agent-action" },
  { source: "Run", target: "运行记录", context: "history" },
  { source: "running", target: "运行中", context: "metric" },
  { source: "paused", target: "已暂停", context: "metric" },
  { source: "error", target: "错误", context: "metric" },
  { source: "errors", target: "错误", context: "metric" },
  { source: "open", target: "未完成", context: "metric" },
  { source: "blocked", target: "已阻塞", context: "metric" },
  { source: "in progress", target: "进行中", context: "status" },
  { source: "planned", target: "已规划", context: "status" },
  { source: "error", target: "错误", context: "status" },
  { source: "failed", target: "失败", context: "status" },
  { source: "succeeded", target: "成功", context: "status" },
  { source: "cancelled", target: "已取消", context: "status" },
  { source: "updated", target: "更新了", context: "activity" },
  { source: "automation", target: "自动触发", context: "run-origin" },
  { source: "assignment", target: "任务分配", context: "run-origin" },
  { source: "on demand", target: "按需", context: "run-origin" },
  { source: "activity", target: "活动", context: "detail-link" },
  { source: "runs", target: "运行记录", context: "detail-link" },
  { source: "costs", target: "费用", context: "detail-link" },
  { source: "budgets", target: "预算", context: "detail-link" },
]);

const timeUnits = { m: "分钟", h: "小时", d: "天", w: "周", mo: "个月", y: "年" };
const dashboardCounts = { running: "运行中", paused: "已暂停", error: "错误", errors: "错误", open: "未完成", blocked: "已阻塞" };
const taskStatuses = { todo: "待办", "in progress": "进行中", "in review": "审核中", done: "已完成", blocked: "已阻塞", cancelled: "已取消", backlog: "待规划", idle: "空闲" };
const searchSortLabels = { relevance: "相关性", "recently updated": "最近更新", "newest created": "最新创建", priority: "优先级" };
const searchScopes = { "all scopes": "所有范围", tasks: "任务", comments: "评论", documents: "文档", artifacts: "产出物", agents: "智能体", projects: "项目" };
const searchFilterLabels = { Status: "状态", Assignee: "负责人", Project: "项目", Label: "标签", Priority: "优先级", Updated: "更新时间" };

export const TEMPLATES = Object.freeze([
  { context: "user-profile", pattern: /^(\S+@\S+) · (owner|member) · (active|inactive) · joined (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) (\d{1,2}), (\d{4})$/, render: (match) => `${match[1]} · ${{ owner: "所有者", member: "成员" }[match[2]]} · ${{ active: "活跃", inactive: "停用" }[match[3]]} · ${match[6]} 年 ${["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"].indexOf(match[4]) + 1} 月 ${match[5]} 日加入` },
  { pattern: /^(\$[\d,.]+) spent$/, render: (match) => `已支出 ${match[1]}` },
  { pattern: /^(\d+)% rate$/, render: (match) => `完成率 ${match[1]}%` },
  { pattern: /^(\d+)% done$/, render: (match) => `完成率 ${match[1]}%` },
  { pattern: /^Click the avatar to upload a new image\. Stored in Paperclip file storage for (.+)\.$/, render: (match) => `点击头像上传新图片。图片将存储在 ${match[1]} 的 Paperclip 文件存储中。` },
  { pattern: /^How should (.+) work\?$/, render: (match) => `${match[1]} 应如何工作？` },
  { pattern: /^Default: (.+)$/, render: (match) => `默认：${match[1] === "Local" || match[1] === "Local machine" ? "本机" : match[1]}` },
  { pattern: /^Installed apps load tools into (.+)'s context on every run\. Permitted-only apps do not add context cost\.$/, render: (match) => `已安装的应用会在每次运行时将工具加入 ${match[1]} 的上下文。仅获准使用、未安装的应用不会增加上下文开销。` },
  { pattern: /^(\d+) of (\d+) enabled$/, render: (match) => `已启用 ${match[1]} / ${match[2]}` },
  { pattern: /^(\d+) total$/, render: (match) => `共 ${match[1]} 条` },
  { pattern: /^(\d+) tools?$/, render: (match) => `${match[1]} 个工具` },
  { pattern: /^Failed run — (.+)$/, render: (match) => `运行失败 — ${match[1]}` },
  { pattern: /^Run (\d{4,})$/, render: (match) => `运行 ${match[1]}` },
  { pattern: /^Transcript \((\d+)\)$/, render: (match) => `对话记录（${match[1]}）` },
  { pattern: /^Events \((\d+)\)$/, render: (match) => `事件（${match[1]}）` },
  { pattern: /^Duration: (\d+)s$/, render: (match) => `耗时：${match[1]} 秒` },
  { pattern: /^Duration: (\d+)m (\d+)s$/, render: (match) => `耗时：${match[1]} 分 ${match[2]} 秒` },
  { pattern: /^Searching for “(.+)”…$/, render: (match) => `正在搜索“${match[1]}”…` },
  { pattern: /^Filter by (Status|Assignee|Project|Label|Priority|Updated)$/, render: (match) => `按${searchFilterLabels[match[1]]}筛选` },
  { pattern: /^No results for “(.+)”$/, render: (match) => `未找到“${match[1]}”的结果` },
  { pattern: /^We couldn’t find a match in (all scopes|tasks|comments|documents|artifacts|agents|projects)\. Try widening the scope or rephrasing your query\.$/, render: (match) => `在${searchScopes[match[1]]}内都没有匹配结果。请扩大搜索范围或换个说法。` },
  { pattern: /^Insert operator ([\w:>" -]+)$/, render: (match) => `插入搜索条件 ${match[1]}` },
  { pattern: /^(\d+)(?: of (\d+))? results? · sorted by (Relevance|Recently updated|Newest created|Priority)(?: · (\d+) filters? active)?$/i, render: (match) => `${match[2] ? `显示 ${match[2]} 条结果中的 ${match[1]} 条` : `${match[1]} 条结果`} · 按${searchSortLabels[match[3].toLowerCase()]}排序${match[4] ? ` · 已启用 ${match[4]} 个筛选条件` : ""}` },
  { pattern: /^(\d+) of (\d+) results$/, render: (match) => `显示 ${match[2]} 条结果中的 ${match[1]} 条` },
  { pattern: /^(\d+) results?$/, render: (match) => `${match[1]} 条结果` },
  { pattern: /^· sorted by (Relevance|Recently updated|Newest created|Priority)$/i, render: (match) => `· 按${searchSortLabels[match[1].toLowerCase()]}排序` },
  { pattern: /^· (\d+) filters? active$/, render: (match) => `· 已启用 ${match[1]} 个筛选条件` },
  { pattern: /^(\d+) agents?$/i, render: (match) => `${match[1]} 个智能体` },
  { pattern: /^(\d+) projects?$/i, render: (match) => `${match[1]} 个项目` },
  { pattern: /^(\d+) tasks?$/i, render: (match) => `${match[1]} 个任务` },
  { pattern: /^(\d+) routines?$/i, render: (match) => `${match[1]} 个例行任务` },
  { pattern: /^(\d+) (running|paused|errors?|open|blocked)$/i, render: (match) => `${match[1]} 个${dashboardCounts[match[2].toLowerCase()]}` },
  { pattern: /^Finished (\d+)(mo|m|h|d|w|y) ago$/, render: (match) => `${match[1]} ${timeUnits[match[2]]}前完成` },
  { pattern: /^(\d+)(mo|m|h|d|w|y) ago$/, render: (match) => `${match[1]} ${timeUnits[match[2]]}前` },
  { pattern: /^updated (\d+)(mo|m|h|d|w|y) ago$/, render: (match) => `${match[1]} ${timeUnits[match[2]]}前更新` },
  { pattern: /^failed · (\d+)(mo|m|h|d|w|y) ago$/, render: (match) => `失败 · ${match[1]} ${timeUnits[match[2]]}前` },
  { pattern: /^(\d+)m (\d+)s · (\d+) tools?$/, render: (match) => `${match[1]} 分 ${match[2]} 秒 · ${match[3]} 个工具` },
  { pattern: /^(\d+)s · (\d+) tools?$/, render: (match) => `${match[1]} 秒 · ${match[2]} 个工具` },
  { pattern: /^Message (.+) — describe what you want done…$/, render: (match) => `给 ${match[1]} 发消息——描述你希望完成的工作…` },
  { pattern: /^The run failed \(([a-z0-9_]+)\)\. You can retry this message now\.$/, render: (match) => `运行失败（${match[1]}）。你现在可以重试这条消息。` },
  { pattern: /^(\d+(?:\.\d+)?[kKmM]?) tokens across request-scoped events$/, render: (match) => `按请求统计的事件共使用 ${match[1]} 个 token` },
  { pattern: /^(\$[\d,.]+) debits · (\$[\d,.]+) credits$/, render: (match) => `支出 ${match[1]} · 抵扣 ${match[2]}` },
  { pattern: /^(\d+) total events in range$/, render: (match) => `所选时段共 ${match[1]} 个事件` },
  { pattern: /^(\$[\d,.]+) estimated in range$/, render: (match) => `所选时段估算 ${match[1]}` },
  { pattern: /^(\d+)m (\d+)s$/, render: (match) => `${match[1]} 分 ${match[2]} 秒` },
  { pattern: /^(\d+)s$/, render: (match) => `${match[1]} 秒` },
  { pattern: /^(\d+) api$/, render: (match) => `${match[1]} 次 API 调用` },
  { pattern: /^(\d+) subscription$/, render: (match) => `${match[1]} 次订阅用量` },
  { pattern: /^changed status to (todo|in progress|in review|done|blocked|cancelled|backlog|idle) on$/i, render: (match) => `将状态改为${taskStatuses[match[1].toLowerCase()]}：` },
  { pattern: /^changed status from (todo|in progress|in review|done|blocked|cancelled|backlog|idle) to (todo|in progress|in review|done|blocked|cancelled|backlog|idle) on$/i, render: (match) => `将状态从${taskStatuses[match[1].toLowerCase()]}改为${taskStatuses[match[2].toLowerCase()]}：` },
  { pattern: /^Connect ([\w -]+) accounts for your agents\.$/, render: (match) => `为智能体连接 ${match[1]} 账户。` },
  { pattern: /^Connect ([\w. -]+)'s provider-hosted MCP server\.$/, render: (match) => `连接 ${match[1]} 托管的 MCP 服务器。` },
  { pattern: /^Use the tools exposed by your ([\w -]+) MCP connection\.$/, render: (match) => `使用 ${match[1]} MCP 连接提供的工具。` },
  { pattern: /^Use ([\w -]+) APIs with a restricted key\.$/, render: (match) => `通过受限密钥使用 ${match[1]} API。` },
  { pattern: /^added reviewer (.+) to$/, render: (match) => `添加 ${match[1]} 为审核人：` },
]);
